module ObjectForge
  module Molds
    def self.wrap_mold
      : ((ObjectForge::mold | Class | nil) mold) -> ObjectForge::mold?
    def self.mold_for
      : (ObjectForge::_Forgable forge_target) -> ObjectForge::mold

    class SingleArgumentMold
      include ObjectForge::_Mold
    end

    class KeywordsMold
      include ObjectForge::_Mold
    end

    class WrappedMold
      interface _MoldClass[T]
        def new: () -> T
      end

      include ObjectForge::_Mold

      attr_reader wrapped_mold: _MoldClass[ObjectForge::mold]

      def initialize: (_MoldClass[ObjectForge::mold] wrapped_mold) -> void
    end

    class StructMold
      interface _StructSubclass[T]
        def new
          : (*untyped) -> T
          | (**Hash[Symbol, untyped]) -> T
          | (Hash[Symbol, untyped]) -> T
        def members: -> Array[Symbol]
        def keyword_init?: -> bool?
      end

      RUBY_FEATURE_AUTO_KEYWORDS: bool
      attr_reader lax: bool

      def initialize: (?lax: bool) -> void

      def call
        : [T < Struct] (forge_target: _StructSubclass[T], attributes: Hash[Symbol, untyped], **untyped) -> T
      
      private
      
      def build_struct_with_unspecified_keyword_init
        : [T < Struct] (_StructSubclass[T] forge_target, Hash[Symbol, untyped] attributes) -> T
    end

    class HashMold
      interface _HashSubclass[T]
        def []: (Hash[Symbol, untyped]) -> T
      end
      interface _Hash[K, X]
        def default=: (X) -> X
        def default_proc=: (Proc?) -> Proc?
      end

      attr_reader default: untyped?
      attr_reader default_proc: Proc?

      def initialize
        : (?untyped? default_value) ?{ (Hash[Symbol, untyped] hash, Symbol key) -> untyped} -> void
      
      def call
        : [X] (forge_target: _HashSubclass[_Hash[Symbol, X]], attributes: Hash[Symbol, untyped], **untyped) -> _Hash[Symbol, X]
    end

    class ArrayMold
      interface _ArraySubclass[T]
        def new: (Array[untyped]) -> T
      end
      interface _Array[X]
      end

      def call
        : [X] (forge_target: _ArraySubclass[_Array[X]], attributes: Hash[Symbol, untyped], **untyped) -> _Array[X]
    end
  end
end
