module ObjectForge
  type forge_target = untyped
  type forge_result = untyped
  type attribute = untyped

  type mold = _RespondTo & _Mold
  type crucible = _RespondTo & (_Crucible | _CrucibleWithYard)
  type sequenceable = _RespondTo & _Sequenceable

  interface _RespondTo
    def respond_to?: (Symbol name, ?bool include_private) -> bool
    def method: (Symbol name) -> ::Method
    def class: -> Class
  end
  interface _Sequenceable
    def succ: -> self
  end
  interface _ForgeParameters
    def attributes: () -> Hash[Symbol, ObjectForge::attribute]
    def traits: () -> Hash[Symbol, Hash[Symbol, ObjectForge::attribute]]
    def options: () -> Hash[Symbol, untyped]
  end
  interface _Mold
    def call
      : (forge_target: ObjectForge::forge_target, attributes: Hash[Symbol, ObjectForge::attribute], **untyped) -> ObjectForge::forge_result
  end
  interface _Crucible
    def call
      : (Hash[Symbol, ObjectForge::attribute]) -> Hash[Symbol, ObjectForge::attribute]
  end
  interface _CrucibleWithYard
    def call
      : (Hash[Symbol, ObjectForge::attribute], ?yard: ObjectForge::_Yard?) -> Hash[Symbol, ObjectForge::attribute]
  end
  interface _Hook
    def call
      : (ObjectForge::forge_result) -> void
  end
  interface _Yard
    def []
      : (Symbol name) -> untyped
    
    def key?
      : (Symbol name) -> bool
  end

  class Error < StandardError
  end
  class DSLError < Error
  end
  class CircularAttributeDependencyError < Error
  end
  class ObjectInterfaceError < ::TypeError
  end

  VERSION: ::String
  DEFAULT_YARD: ObjectForge::Forgeyard

  def self.sequence
    : ((ObjectForge::sequenceable | ObjectForge::Sequence) initial) -> ObjectForge::Sequence

  def self.define
    : (Symbol name, ObjectForge::forge_target) { (ObjectForge::ForgeDSL) -> void } -> ObjectForge::Forge
    | (Symbol name, ObjectForge::forge_target) { [self: ObjectForge::ForgeDSL] -> void } -> ObjectForge::Forge

  def self.forge
    : (Symbol name, *Symbol traits, **ObjectForge::attribute overrides) ?{ (ObjectForge::forge_result) -> void } -> ObjectForge::forge_result
  def self.build
    : (Symbol name, *Symbol traits, **ObjectForge::attribute overrides) ?{ (ObjectForge::forge_result) -> void } -> ObjectForge::forge_result
  def self.call
    : (Symbol name, *Symbol traits, **ObjectForge::attribute overrides) ?{ (ObjectForge::forge_result) -> void } -> ObjectForge::forge_result
end

class ObjectForge::Sequence
  def self.new
    : ((ObjectForge::sequenceable | ObjectForge::Sequence) initial) -> ObjectForge::Sequence
  
  attr_reader initial: ObjectForge::sequenceable
  
  def initialize: (ObjectForge::sequenceable initial) -> void

  def next: -> ObjectForge::sequenceable

  def reset: -> ObjectForge::sequenceable
  alias rewind reset
end
  
class ObjectForge::Forgeyard
  attr_reader forges: Concurrent::Map[Symbol, ObjectForge::Forge]

  def initialize
    : () -> void

  def define
    : (Symbol name, ObjectForge::forge_target) { (ObjectForge::ForgeDSL) -> void } -> ObjectForge::Forge
    | (Symbol name, ObjectForge::forge_target) { [self: ObjectForge::ForgeDSL] -> void } -> ObjectForge::Forge

  def register
    : (Symbol name, ObjectForge::Forge forge) -> ObjectForge::Forge
  
  def []
    : (Symbol name) -> ObjectForge::Forge
  
  def key?
    : (Symbol name) -> bool

  def forge
    : (Symbol name, *Symbol traits, **ObjectForge::attribute overrides) ?{ (ObjectForge::forge_result) -> void } -> ObjectForge::forge_result
  alias build forge
  alias call forge
end

class ObjectForge::Forge
  class Parameters < Struct[Hash[Symbol, untyped]]
    include ObjectForge::_ForgeParameters

    # Struct allows skipping arguments, but in reality they are all required.
    def initialize
      : (attributes: Hash[Symbol, ObjectForge::attribute], traits: Hash[Symbol, Hash[Symbol, ObjectForge::attribute]], options: Hash[Symbol, untyped]) -> void
  end

  attr_reader name: Symbol?

  attr_reader yard: ObjectForge::_Yard?

  attr_reader forge_target: ObjectForge::forge_target
  alias target forge_target

  attr_reader parameters: ObjectForge::_ForgeParameters

  @crucible: ObjectForge::crucible
  @mold: ObjectForge::_Mold
  @after_forge_hook: ObjectForge::_Hook?

  def self.define
    : (ObjectForge::forge_target, ?name: Symbol?, ?yard: ObjectForge::_Yard?) { (ObjectForge::ForgeDSL) -> void } -> ObjectForge::Forge
    | (ObjectForge::forge_target, ?name: Symbol?, ?yard: ObjectForge::_Yard?) { [self: ObjectForge::ForgeDSL] -> void } -> ObjectForge::Forge
  
  def initialize
    : (ObjectForge::forge_target, ObjectForge::_ForgeParameters parameters, ?name: Symbol?, ?yard: ObjectForge::_Yard?) -> void
  
  def forge
    : (*Symbol traits, **ObjectForge::attribute overrides) ?{ (ObjectForge::forge_result) -> void } -> ObjectForge::forge_result
  alias build forge
  alias call forge

  private
  
  def determine_crucible
    : (Hash[Symbol, untyped]) -> ObjectForge::crucible

  def crucible_takes_yard_parameter?
    : (ObjectForge::crucible) -> bool

  def determine_mold
    : (ObjectForge::forge_target, Hash[Symbol, untyped]) -> ObjectForge::mold

  def determine_after_forge_hook
    : (Hash[Symbol, untyped] options) -> ObjectForge::_Hook?
  
  def validate_other_options
    : (Hash[Symbol, untyped] options) -> void

  def build_attribute_hash
    : (Array[Symbol] traits, Hash[Symbol, ObjectForge::attribute] overrides) -> Hash[Symbol, ObjectForge::attribute]

  def resolve_attributes
    : (Array[Symbol] traits, Hash[Symbol, ObjectForge::attribute] overrides) -> Hash[Symbol, ObjectForge::attribute]

  def apply_attribute_list
    : (Hash[Symbol, ObjectForge::attribute] attributes) -> Hash[Symbol, ObjectForge::attribute]
end

class ObjectForge::ForgeDSL < ObjectForge::UnBasicObject
  include ObjectForge::_ForgeParameters

  attr_reader sequences: Hash[Symbol, ObjectForge::Sequence]

  @attributes: Hash[Symbol, Proc]
  @sequences: Hash[Symbol, ObjectForge::Sequence]
  @traits: Hash[Symbol, Hash[Symbol, Proc]]
  @options: Hash[Symbol, untyped]
  @transient_attributes: Array[Symbol]

  def initialize
    : () { (ObjectForge::ForgeDSL) -> void } -> void
    | () { [self: ObjectForge::ForgeDSL] -> void } -> void

  def freeze: -> self

  def option
    : (Symbol name, untyped value) -> Symbol

  def attribute
    : (Symbol name, ?transient: bool) { [self: ObjectForge::Crucible] -> ObjectForge::attribute } -> Symbol
  alias [] attribute

  def transient
    : (Symbol name) { [self: ObjectForge::Crucible] -> ObjectForge::attribute } -> Symbol

  def sequence
    : (Symbol name, ?(ObjectForge::sequenceable | ObjectForge::Sequence) initial, ?transient: bool) { (ObjectForge::sequenceable) [self: ObjectForge::Crucible] -> ObjectForge::attribute } -> Symbol
    | (Symbol name, ?(ObjectForge::sequenceable | ObjectForge::Sequence) initial, ?transient: bool) -> Symbol

  def trait
    : (Symbol name) { (self) -> void } -> Symbol

  def inspect: -> String
  
  private

  def method_missing
    # Attribute shortcut:
    : (Symbol name) { [self: ObjectForge::Crucible] -> ObjectForge::attribute } -> Symbol
    # Option shortcut:
    | (Symbol name, untyped value) -> Symbol
    # After freezing:
    | (Symbol name) ?{ -> untyped } -> void

  def respond_to_missing?
    : (Symbol name, bool include_all) -> bool
  
  def valid_option_method?
    : (Symbol name) -> bool
  
  def shape_attribute_list!
    : -> void
end

class ObjectForge::Crucible < ObjectForge::UnBasicObject
  EMPTY_YARD: Hash[Symbol, untyped]

  def self.call
    : (Hash[Symbol, ObjectForge::attribute], ?yard: ObjectForge::_Yard?) -> Hash[Symbol, ObjectForge::attribute]
  def self.resolve
    : (Hash[Symbol, ObjectForge::attribute], ?yard: ObjectForge::_Yard?) -> Hash[Symbol, ObjectForge::attribute]

  @attributes: Hash[Symbol, ObjectForge::attribute]
  @resolved_attributes: Set[Symbol]
  @resolving_attributes: Array[Symbol]

  attr_reader yard: ObjectForge::_Yard

  def initialize
    : (Hash[Symbol, ObjectForge::attribute] attributes, ?yard: ObjectForge::_Yard?) -> void

  def resolve!
    : -> Hash[Symbol, ObjectForge::attribute]

  private

  def method_missing
    : (Symbol name) -> ObjectForge::attribute
  alias [] method_missing

  def respond_to_missing?
    : (Symbol name, bool include_all) -> bool
  
  def raise_circular_dependency_error!
    : (Symbol name) -> void
  
  def resolve_attribute!
    : (Symbol name) -> void
end

class ObjectForge::UnBasicObject < BasicObject
  def class: -> Class
  
  def eql?: (untyped other) -> bool

  def freeze: -> self

  def frozen?: -> bool

  def hash: -> Integer

  def inspect: -> String

  def is_a?: (Module klass) -> bool
  def kind_of?: (Module klass) -> bool

  def respond_to?: (Symbol name, ?bool include_all) -> bool

  def to_s: -> String

  def pretty_print: (PP) -> void

  def pretty_print_cycle: (PP) -> void
  
  private

  def block_given?: -> bool

  def raise: (_Exception exception, ?String message, ?Array[String] backtrace, ?cause: _Exception) -> void

  def respond_to_missing?: (Symbol name, bool include_all) -> bool
end
