name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '53 4 * * TUE'
jobs:
  CRuby:
    uses: ./.github/workflows/cruby.yaml
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'development'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rake rubocop
  signatures:
    name: RBS
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'development'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Run RBS
      run: bundle exec rake rbs
  coverage:
    name: Coverage report for PR
    if: ${{ github.event_name == 'pull_request' }}
    needs: CRuby
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake spec
    - name: Add code coverage comment
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: ./coverage/lcov/object_forge.lcov
        delete-old-comments: true
